name: pygaggle
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - blas=1.0
  - ca-certificates=2020.1.1
  - certifi=2020.4.5.1
  - freetype=2.9.1
  - intel-openmp=2020.0
  - jpeg=9b
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - mkl=2020.0
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - ncurses=6.2
  - ninja=1.9.0
  - numpy-base=1.18.1
  - olefile=0.46
  - openssl=1.1.1f
  - pillow=7.0.0
  - pip=20.0.2
  - python=3.7.7
  - readline=8.0
  - setuptools=46.1.3
  - six=1.14.0
  - sqlite=3.31.1
  - tk=8.6.8
  - wheel=0.34.2
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - absl-py==0.9.0
    - astor==0.8.1
    - blis==0.4.1
    - boto3==1.12.41
    - botocore==1.15.41
    - cachetools==4.1.0
    - catalogue==1.0.0
    - chardet==3.0.4
    - click==7.1.1
    - coloredlogs==14.0
    - cymem==2.0.3
    - cython==0.29.16
    - docutils==0.15.2
    - filelock==3.0.12
    - gast==0.2.2
    - google-auth==1.14.0
    - google-auth-oauthlib==0.4.1
    - google-pasta==0.2.0
    - grpcio==1.28.1
    - h5py==2.10.0
    - humanfriendly==8.2
    - idna==2.9
    - importlib-metadata==1.6.0
    - jmespath==0.9.5
    - joblib==0.14.1
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.0
    - markdown==3.2.1
    - murmurhash==1.0.2
    - numpy==1.18.2
    - oauthlib==3.1.0
    - opt-einsum==3.2.1
    - plac==1.1.3
    - preshed==3.0.2
    - protobuf==3.11.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydantic==1.5
    - pyjnius==1.2.1
    - pyserini==0.9.0.0
    - python-dateutil==2.8.1
    - regex==2020.4.4
    - requests==2.23.0
    - requests-oauthlib==1.3.0
    - rsa==4.0
    - s3transfer==0.3.3
    - sacremoses==0.0.41
    - scikit-learn==0.22.2.post1
    - scipy==1.4.1
    - sentencepiece==0.1.85
    - sklearn==0.0
    - spacy==2.2.4
    - srsly==1.0.2
    - tensorboard==2.1.1
    - tensorflow==2.1.0
    - tensorflow-estimator==2.1.0
    - tensorflow-gpu==2.1.0
    - tensorflow-text==2.1.1
    - termcolor==1.1.0
    - thinc==7.4.0
    - tokenizers==0.5.2
    - tqdm==4.45.0
    - transformers==2.7.0
    - urllib3==1.25.9
    - wasabi==0.6.0
    - werkzeug==1.0.1
    - wrapt==1.12.1
    - zipp==3.1.0
