name: pygaggle
channels:
  - defaults
dependencies:
  - python=3.8
  - conda-forge::openjdk
  - conda-forge::tensorflow
  - pip:
    - coloredlogs==14.0
    - dataclasses;python_version<"3.7"
    - numpy>=1.18
    - pydantic==1.7.4
    - pyserini>=0.16.0
    - scikit-learn==0.24.2
    - scipy==1.5.4
    - spacy>=3.2.1
    - tokenizers==0.10.2
    - tqdm==4.56.0
    - transformers==4.6.1
    - sentencepiece==0.1.95
    - sentence_transformers==2.0.0
    - torch>=1.8.1
    - faiss-cpu>=1.7.3